boxes.append(
    { :name => "{{lab_name}}-GUACAMOLE",
      :ip => "{{ip_range}}.52",
      :box => "bento/ubuntu-22.04", 
      :os => "linux",
      :cpus => 2,
      :mem => 3000,
      :forwarded_port => [ {:guest => 22, :host => 2210, :id => "ssh"} ]
    }
)