boxes.append(
    { :name => "{{lab_name}}-WAZUH",
      :ip => "{{ip_range}}.51",
      :box => "bento/ubuntu-22.04", 
      :os => "linux",
      :cpus => 2,
      :mem => 8000,
      :forwarded_port => [ {:guest => 22, :host => 2210, :id => "ssh"} ]
    }
)