boxes.append(
    { :name => "{{lab_name}}-LX01",
      :ip => "{{ip_range}}.32",
      :box => "bento/ubuntu-22.04", 
      :os => "linux",
      :cpus => 1,
      :mem => 1000,
      :forwarded_port => [ {:guest => 22, :host => 2210, :id => "ssh"} ]
    }
)