boxes = [
  # windows server 2019
  { :name => "GOAD-Mini-DC01",  :ip => "{{ip_range}}.10", :box => "jborean93/WindowsServer2019", :box_version => "1.2.0", :os => "windows", :cpus => 2, :mem => 3000}
]
