- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Restart SSSD
  systemd:
    name: sssd
    state: restarted

- name: Restart timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted