variable "proxmox_url" {}
variable "proxmox_username" {}
variable "proxmox_password" {}
variable "proxmox_skip_tls_verify" {}
variable "proxmox_node" {}
variable "proxmox_pool" {}
variable "proxmox_vm_storage" {}
variable "proxmox_iso_storage" {}
variable "winrm_username" {}
variable "winrm_password" {}
variable "proxmox_bridge" {}
variable "vm_name" {}
variable "template_description" {}
variable "iso_file" {}
variable "autounattend_iso" {}
variable "virtio_iso" {}
variable "scripts_iso" {}
variable "iso_checksum" {}
variable "autounattend_checksum" {}
variable "virtio_checksum" {}
variable "scripts_checksum" {}
variable "vm_cpu_cores" {}
variable "vm_cpu_type" {}
variable "vm_machine" {}
variable "vm_memory" {}
variable "vm_disk_size" {}
variable "vm_disk_format" {}
variable "vm_sockets" {}
variable "os" {}
variable "bios" {}