boxes = [
  # windows server 2019
  { :name => "GOAD-Light-DC01",  :ip => "{{ip_range}}.10", :box => "jborean93/WindowsServer2019", :box_version => "1.2.0", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2019
  { :name => "GOAD-Light-DC02",  :ip => "{{ip_range}}.11", :box => "jborean93/WindowsServer2019", :box_version => "1.2.0", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2019
  { :name => "GOAD-Light-SRV02", :ip => "{{ip_range}}.22", :box => "jborean93/WindowsServer2019", :box_version => "1.2.0", :os => "windows", :cpus => 2, :mem => 6000},
]
