- name: Disable NTLM minimum server session security (MAQ server)
  ansible.windows.win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    name: NtlmMinServerSec
    type: dword
    data: 0