boxes = [
  { :name => "NHA-DC01",   :ip => "192.168.58.10", :box => "mayfly/windows_server2019", :os => "windows", :cpus => 2, :mem => 3000},
  { :name => "NHA-DC02",   :ip => "192.168.58.20", :box => "mayfly/windows_server2019", :os => "windows", :cpus => 2, :mem => 3000},
  { :name => "NHA-SRV01",  :ip => "192.168.58.21", :box => "mayfly/windows_server2019", :os => "windows", :cpus => 2, :mem => 5000},
  { :name => "NHA-SRV02",  :ip => "192.168.58.22", :box => "mayfly/windows_server2019", :os => "windows", :cpus => 2, :mem => 5000},
  { :name => "NHA-SRV03",  :ip => "192.168.58.23", :box => "mayfly/windows_server2019", :os => "windows", :cpus => 2, :mem => 3000}
]
