boxes = [
  # windows server 2019
  { :name => "GOADL-DC01",  :ip => "192.168.56.10", :box => "StefanScherer/windows_2019", :box_version => "2021.05.15", :os => "windows", :cpus => 2, :mem => 3000},
  # windows server 2019
  { :name => "GOADL-DC02",  :ip => "192.168.56.11", :box => "StefanScherer/windows_2019", :box_version => "2021.05.15", :os => "windows" :cpus => 2, :mem => 3000},
  # windows server 2019
  { :name => "GOADL-SRV02", :ip => "192.168.56.22", :box => "StefanScherer/windows_2019", :box_version => "2021.05.15", :os => "windows" :cpus => 2, :mem => 4000},
]