Vagrant.configure("2") do |config|

  # Uncomment this depending on the provider you want to use
  ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'
  
  boxes = [
    { :name => "DC01",  :ip => "192.168.56.30", :box => "jborean93/WindowsServer2019", :os => "windows"},
    { :name => "SRV01", :ip => "192.168.56.31", :box => "jborean93/WindowsServer2019", :os => "windows"}
  ]

  # Recommended boxes
  # Windows server 2019 (180days)
  #{ :name => "X", :ip => "192.168.56.x", :box => "jborean93/WindowsServer2019", :os => "windows"},
  #{ :name => "X", :ip => "192.168.56.x", :box => "StefanScherer/windows_2019", :box_version => "2021.05.15", :os => "windows"},
  #{ :name => "X", :ip => "192.168.56.x", :box => "StefanScherer/windows_2019", :box_version => "2020.07.17", :os => "windows"},
  # Windows server 2016 (180days)
  #{ :name => "X", :ip => "192.168.56.x", :box => "StefanScherer/windows_2016", :box_version => "2017.12.14", :os => "windows"},
  #{ :name => "X", :ip => "192.168.56.x", :box => "StefanScherer/windows_2016", :box_version => "2019.02.14", :os => "windows"},
  # Windows 10 (90days)
  # TODO

  config.vm.provider "virtualbox" do |v|
    v.memory = 4000
    v.cpus = 2
  end

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "4000"
    v.vmx["numvcpus"] = "2"
  end

  # disable forwarded port
  config.vm.network "forwarded_port", guest: 3389, host: 3389, id: 'rdp', auto_correct: true, disabled: true
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: 'ssh', auto_correct: true, disabled: true

  # no autoupdate if vagrant-vbguest is installed
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  boxes.each do |box|
    config.vm.define box[:name] do |target|
      # BOX
      target.vm.provider "virtualbox" do |v|
        v.name = box[:name]
      end
      target.vm.box_download_insecure = box[:box]
      target.vm.box = box[:box]
      if box.has_key?(:box_version)
        target.vm.box_version = box[:box_version]
      end

      # issues/49
      target.vm.synced_folder '.', '/vagrant', disabled: true

      # IP
      target.vm.network :private_network, ip: box[:ip]

      # OS specific
      if box[:os] == "windows"
        target.vm.guest = :windows
        target.vm.communicator = "winrm"
        target.vm.provision :shell, :path => "../../../../vagrant/Install-WMF3Hotfix.ps1", privileged: false
        target.vm.provision :shell, :path => "../../../../vagrant/ConfigureRemotingForAnsible.ps1", privileged: false

        # fix ip for vmware
        if ENV['VAGRANT_DEFAULT_PROVIDER'] == "vmware_desktop"
          target.vm.provision :shell, :path => "../../../../vagrant/fix_ip.ps1", privileged: false, args: box[:ip]
        end

      else
        target.vm.communicator = "ssh"
      end

      if box.has_key?(:forwarded_port)
        # forwarded port explicit
        box[:forwarded_port] do |forwarded_port|
          target.vm.network :forwarded_port, guest: forwarded_port[:guest], host: forwarded_port[:host], host_ip: "127.0.0.1", id: forwarded_port[:id]
        end
      end

    end
  end
end