Vagrant.configure("2") do |config|

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'vmware_desktop'

boxes = [
  { :name => "SCCM-DC",  :ip => "192.168.33.10", :box => "mayfly/windows_server2019", :cpu => 2, :ram => 4000, :os => "windows"},
  { :name => "SCCM-MECM" , :ip => "192.168.33.11", :box => "mayfly/windows_server2019", :cpu => 2, :ram => 4000, :os => "windows"},
  { :name => "SCCM-MSSQL", :ip => "192.168.33.12", :box => "mayfly/windows_server2019", :cpu => 2, :ram => 4000, :os => "windows"},
  { :name => "SCCM-CLIENT",  :ip => "192.168.33.13", :box => "mayfly/windows_server2019", :cpu => 2, :ram => 4000, :os => "windows"},
]

if ENV.has_key?('GOAD_VAGRANT_OPTIONS') and ENV['GOAD_VAGRANT_OPTIONS'].include? "elk"
  boxes.append(
    { :name => "GOAD-ELK", :ip => "192.168.33.50", :box => "bento/ubuntu-18.04", :os => "linux", :forwarded_port => [
      {:guest => 22, :host => 2210, :id => "ssh"} ]
    }
  )
end

  # disable rdp forwarded port inherited from StefanScherer box
  config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true, disabled: true

  # no autoupdate if vagrant-vbguest is installed
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600
  config.winrm.retry_limit = 30
  config.winrm.retry_delay = 10

  boxes.each do |box|
    config.vm.define box[:name] do |target|
      # BOX
      target.vm.provider "virtualbox" do |v|
        v.name = box[:name]
        v.memory = box[:ram]
        v.cpus = box[:cpu]
        v.customize ["modifyvm", :id, "--groups", "/GOAD"]
      end

      target.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = box[:ram]
        v.vmx["numvcpus"] = box[:cpu]
        v.force_vmware_license = "workstation"  # force the licence for fix some vagrant plugin issue
      end

      target.vm.box_download_insecure = box[:box]
      target.vm.box = box[:box]
      if box.has_key?(:box_version)
        target.vm.box_version = box[:box_version]
      end

      # issues/49
      target.vm.synced_folder '.', '/vagrant', disabled: true

      # IP
      target.vm.network :private_network, ip: box[:ip]

      # OS specific
      if box[:os] == "windows"
        target.vm.guest = :windows
        target.vm.communicator = "winrm"
        target.vm.provision :shell, :path => "../../../../vagrant/Install-WMF3Hotfix.ps1", privileged: false
        target.vm.provision :shell, :path => "../../../../vagrant/ConfigureRemotingForAnsible.ps1", privileged: false

        # fix ip for vmware
        if ENV['VAGRANT_DEFAULT_PROVIDER'] == "vmware_desktop"
          target.vm.provision :shell, :path => "../../../../vagrant/fix_ip.ps1", privileged: false, args: box[:ip]
        end

      else
        target.vm.communicator = "ssh"
      end

      if box.has_key?(:forwarded_port)
        # forwarded port explicit
        box[:forwarded_port] do |forwarded_port|
          target.vm.network :forwarded_port, guest: forwarded_port[:guest], host: forwarded_port[:host], host_ip: "127.0.0.1", id: forwarded_port[:id]
        end
      end

    end
  end
end
