---
- name: "Disable vagrant"
  hosts: domain
  roles:
    - { role: 'disable_user', tags: 'disable_vagrant', username: "vagrant"}

- name: "Disable vagrant"
  hosts: linux_domain
  become: yes
  roles:
    - { role: 'linux/disable_user', tags: 'disable_vagrant', username: "vagrant"}