---
# Load datas
- import_playbook: data.yml
  vars:
    data_path: "../ad/{{domain_name}}/data/"
  tags: 'data'

# set AD datas ==================================================================================================
- name: DCs AD data configuration
  hosts: dc01,dc02
  roles:
    - { role: 'onlyusers', tags: 'onlyusers' }
  vars:
    hostname: "{{lab.hosts[inventory_hostname].hostname}}"
    domain: "{{lab.hosts[inventory_hostname].domain}}"
    domain_username: "{{domain}}\\Administrator"
    domain_password: "{{lab.domains[domain].domain_password}}"
    domain_server: "{{lab.hosts[inventory_hostname].hostname}}.{{domain}}"
    ad_users: "{{lab.domains[lab.hosts[inventory_hostname].domain].users}}"
    ad_ou: "{{lab.domains[lab.hosts[inventory_hostname].domain].organisation_units}}"
    ad_groups: "{{lab.domains[lab.hosts[inventory_hostname].domain].groups}}"
