- name: update apt cache
  apt: update_cache=yes

- name: Install AD Packages
  apt:
    name:
      - sssd-ad
      - sssd-tools
      - realmd
      - adcli
      - packagekit
    state: present

- name: Create KRB5 File
  copy:
    dest: "/etc/krb5.conf"
    content: |
      [libdefaults]
      default_realm = {{ domain |upper}}
      ticket_lifetime = 24h
      renew_lifetime = 7d
      dns_lookup_realm = true
      dns_lookup_kdc = true
      forward = true
      forwardable = true

      [realms]
      {{ domain  |upper }} = {
        admin_server = {{ dc_fqdn  |upper}}
        kdc = {{ dc_fqdn  |upper}}
      }

      [domain_realm]
      {{ domain }} =  {{ domain|upper }}
      .{{ domain }} = {{ domain|upper }}

- name: Install krb5 Packages
  apt:
    name:
      - krb5-user
      - sssd-krb5
    state: present

- name: Modify Hosts File to add current hostname
  lineinfile:
    dest: "/etc/hosts"
    line: "127.0.1.1       {{ hostname }}.{{ domain }}"
    state: present
    backup: yes

- name: Modify Hosts File to add domain dc 
  lineinfile:
    dest: "/etc/hosts"
    line: "{{dc_ip}}       {{ dc_fqdn }}  {{ domain }}"
    state: present
    backup: yes

- name: Modify Hostname
  shell:
    "sudo hostnamectl set-hostname {{ hostname }}.{{ domain }}"

- name: Kinit
  shell:
    "echo {{ domain_password }} | sudo kinit {{ domain_username }}"
  register: result

- name: Print Kinit Result
  debug: var=result.stdout_lines

- name: Check if domain joined
  shell:
    "realm list"
  register: domain_joined

- name: Print realm list Result
  debug: var=domain_joined.stdout_lines

- name: Join Realm
  shell:
    "echo {{ domain_password }} | sudo realm join -v -U {{ domain_username }} {{ domain }}"
  when: not domain in domain_joined.stdout_lines
  register: result

- name: Print Realm Result
  debug: var=result.stdout_lines
  when: not domain in domain_joined.stdout_lines

- name: Activate Homedir Creation
  shell:
    "sudo pam-auth-update --enable mkhomedir"

- name: Modify SSDCONF Line 1 Ubuntu
  replace:
    path: /etc/sssd/sssd.conf
    regexp: 'use_fully_qualified_names = True'
    replace: 'use_fully_qualified_names = False'

- name: Modify SSDCONF Line 2 Ubuntu
  replace:
    path: /etc/sssd/sssd.conf
    regexp: 'fallback_homedir = /home/%u@%d'
    replace: 'fallback_homedir = /home/%u'

- name: Add {{ item }} to Sudoers Ubuntu
  lineinfile:
    dest: "/etc/sudoers"
    line: "%{{ item }}   ALL=(ALL) NOPASSWD:ALL"
    state: present
    validate: /usr/sbin/visudo -cf %s
    backup: yes
  loop: "{{sudoers_group}}"

- name: Allow {{ item }} Login Ubuntu
  shell:
    "realm permit -g {{ item }}@{{ domain }}"
  loop: "{{ssh_group}}"

- name: Enable GSSAPI Authentication in SSHD
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?GSSAPIAuthentication'
    line: 'GSSAPIAuthentication yes'
    state: present
    backup: yes

- name: Enable GSSAPI Cleanup Credentials
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?GSSAPICleanupCredentials'
    line: 'GSSAPICleanupCredentials yes'
    state: present
    backup: yes

- name: Disable GSSAPIStrictAcceptorCheck
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?GSSAPIStrictAcceptorCheck'
    line: 'GSSAPIStrictAcceptorCheck no'
    state: present
    backup: yes

- name: Ensure PAM is enabled in SSHD
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?UsePAM'
    line: 'UsePAM yes'
    state: present
    backup: yes

- name: Install PAM Kerberos module
  apt:
    name: libpam-krb5
    state: present
  notify: Restart SSH

- name: Add ssh
  shell:
    "sudo realm join --client-software=sssd {{ domain }}"
  ignore_errors: yes

- name: Define domain DNS in resolved.conf
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNS='
    line: "DNS={{dc_ip}}"

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted

- name: Fix symlink resolv.conf
  file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes

- name: Install ntpdate
  ansible.builtin.apt:
    name: ntpdate
    state: present
    update_cache: true

- name: Force immediate time sync with DC
  ansible.builtin.command:
    cmd: "ntpdate -u {{ dc_ip }}"

- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present
    update_cache: yes

- name: Configure DC as NTP server
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: '^server {{ dc_ip }}'
    line: "server {{ dc_ip }} iburst"
    state: present
    insertafter: EOF
  notify:
    - Restart chrony

- name: Remove default Ubuntu NTP pools
  ansible.builtin.replace:
    path: /etc/chrony/chrony.conf
    regexp: '^pool .*$'
    replace: ''
  notify:
    - Restart chrony

- name: Set makestep to 1 -1
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: '^makestep'
    line: "makestep 1 -1"
    state: present
  notify:
    - Restart chrony

- name: Ensure chrony is started and enabled
  ansible.builtin.systemd:
    name: chrony
    state: started
    enabled: yes

- name: Set RTC in local timezone and adjust system clock
  ansible.builtin.command:
    cmd: timedatectl set-local-rtc 1 --adjust-system-clock

- name: Force immediate time sync
  ansible.builtin.command:
    cmd: chronyc -a makestep

- name: Remove faulty ad_server line to enable auto-discovery
  lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: '^ad_server\s*='
    state: absent
    backup: yes
  notify:
    - Restart SSSD